# This is the first pipeline in the set of two pipelines.

# It is responsible for trigging a TBS build when code is commited
# to the main branch.

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Run_CI_Tests
  jobs:
    - job: 
      steps:
        # We're just doing a build image here to 
        # run all the tests for simplicity sake
        #- script: ./mvnw spring-boot:build-image
        - script: echo "Run CI Tests"

- stage: Image_Build
  jobs:
    - job: Image_Build_Job
      steps:
        - script: |
            curl -L https://github.com/pivotal-cf/pivnet-cli/releases/download/v3.0.1/pivnet-linux-amd64-3.0.1 -o pivnet
            chmod u+x pivnet
          displayName: 'Download Tanzu Network CLI'
        - script: ./pivnet login --api-token $(api-token)
          displayName: 'Log in to the Tanzu Network'
        - script: | 
            ./pivnet download-product-files --product-slug='build-service' --release-version='1.2.1' --product-file-id=970671
            mv kp-linux-0.3.0 kp
            chmod u+x kp
          displayName: 'Download kpack cli'
        # kpack requires kubectl to be setup, and we can't use the 
        # service connection because the kubectl task creates and deletes
        # the kubectl file during each task so we must manually create 
        # a kubectl config file
        - script: |
            kubectl config set-cluster demo --server=$(k8s-server)
            kubectl config set-credentials azure-pipelines --token=$(k8s-token)
            kubectl config set-context demo --user=azure-pipelines --cluster=demo
            kubectl config set-cluster demo --embed-certs --certificate-authority <(echo $(k8s-ca-crt-b64) | base64 --decode)
            kubectl config use-context demo
          displayName: Setup Kubectl
        # Patch the image with the git commit sha so that TBS will build the image.
        # Pipe the results to a file so we can capture the sha of the docker image
        # for subsequent deployments

        # For some reason with Azure DevOps passing the sha variable directly to
        # the task.setvariable function wasn't working.  It was just passing a blank
        # value.  Writing to output.txt then cat'ing that worked around that issue.
        - script: | 
            ./kp image patch --git-revision=$(Build.SourceVersion) --wait spring-petclinic | tee imagebuild.output
          name: patch_image
        - script: |
            echo "Key Value :"
            echo $(patch_image.sha)
          name: Print_Key_value